#+TITLE: Emacs Text Property: Display
#+AUTHOR: Cameron Smith - <cjonsmith@gmail.com>

When reading the manual for Info, I noticed that the text that is written in the info file
does not always match what is displayed in the info window. For example, on the node `(info)
Help-Xref', the visible text on the first cross-reference is:

> see Cross

But the text when viewing the source file (can be done by using the function `find-file',
usually bound to `C-x f' and looking for `info-info.gz'):

> *Note Cross: Help-Cross

Similar to how Menus begin with a line consisting only of `* Menu', which also does not get
displayed in the info view (unless `visible-mode' is enabled or `Info-hide-note-references'
is set to an appropriate value), the `*Note' syntax seems to correspond to a cross-reference
(I couldn't find anything conclusive in the `(texinfo) Cross References' info node).

Another weird oddity of the `see Cross' text is that when I put the cursor over the `s' in
`see' and then invoked `forward-char' (bound to `C-x f` by default), the cursor would jump
all the way to the `C' in `Cross'. I had recently discovered the `what-cursor-position'
function when trying to the increase my font size (`text-scale-adjust' is bound to `C-x C-='
by default, and `what-cursor-position' is bound to `C-x =' by default), so I expected that
invoking it on the `s' in `see' would provide some information about what was going on
under-the-hood here:

> Char: * (42, #o52, #x2a, ASTERISK, part of display "*Not..."->"see ") point=26673 of 83354 (32%) <26426-30072> column=27

(Note: The fourth entry in the list contains the word `ASTERISK', which may not be displayed
by default in your copy of Emacs. I have the variable `what-cursor-show-names' set to a
non-nil value, which signals to `what-cursor-position' to show the name of the character under
the cursor. It isn't pertainant here, so it's not required to be set in order to follow
along.)

So sure enough, we're seeing that the _actual_ character under the cursor is an `*', not an
`s'. This aligns with what we're seeing in the source texinfo file, but how is `see' getting
displayed in its place? Let's take a closer look at the documentation of
`what-cursor-position' to see if there's anything else we could gleam from the function:

> ...
> In addition, with prefix argument, show details about that character
> in *Help* buffer.  See also the command ‘describe-char’.

Alright, sounds promising. Let's try passing the prefix argument (`C-u') to our call to
`what-cursor-position' when placing the cursor over the `s' (the keystokes are `C-u C-x ='):

```
             position: 26673 of 83354 (32%), restriction: <26426-30072>, column: 27
            character: * (displayed as *) (codepoint 42, #o52, #x2a)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x2A
               script: latin
               syntax: _ 	which means: symbol
             category: .:Base, a:ASCII, l:Latin, r:Roman
             to input: type "C-x 8 RET 2a" or "C-x 8 RET ASTERISK"
          buffer code: #x2A
            file code: #x2A (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    ftcrhb:-ADBO-Source Code Pro-normal-normal-normal-*-16-*-*-*-m-0-iso10646-1 (#x3CB)

Character code properties: customize what to show
  name: ASTERISK
  general-category: Po (Punctuation, Other)
  decomposition: (42) ('*')

There are text properties here:
  display              "see "
  fontified            t
  front-sticky         nil
  rear-nonsticky       t

[back]
```

A new *Help* buffer is opened, and a lot of not-so-pertainant info is given. However, at the
bottom there is a section that lists what "text properties" are applied to the current
character, one of which is called `display'.
